name: Nim CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install curl
      run: sudo apt update && sudo apt install curl -y
    - name: setup choosenim
      run: ./setupci.sh
    - name: Update nimble
      run: .nimble/bin/nimble update
    - name: Build INim
      run: .nimble/bin/nimble build
    - name: Run tests
      run: .nimble/bin/nimble test -d:prompt_no_history
